In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv('data/dataset_regression_cleaned.csv')

In [10]:
# define a function called "outliers" which returns a list of index of outliers
# Use Inter-quartile Range(IQR) to detect ourliers
# IQR = Q3-Q1
# +/- 1.5*IQR

def outliers(df, variable):
    Q1 = df[variable].quantile(0.30)
    Q3 = df[variable].quantile(0.70)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR

    ls = df.index[(df[variable] < lower_bound) | (df[variable] > upper_bound)]
    return ls

In [11]:
# create an empty list to store the output indice from multiple columns
index_list = []
for variable in ['Price']:
    index_list.extend(outliers(df, variable))

In [12]:
index_list

[6,
 7,
 18,
 26,
 27,
 28,
 29,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 97,
 98,
 99,
 105,
 106,
 107,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 123,
 124,
 135,
 136,
 137,
 144,
 145,
 151,
 155,
 164,
 165,
 169,
 187,
 190,
 218,
 223,
 225,
 240,
 241,
 242,
 244,
 247,
 248,
 254,
 255,
 256,
 257,
 258,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 294,
 295,
 300,
 301,
 307,
 317,
 319,
 320,
 326,
 329,
 341,
 347,
 348,
 349,
 350,
 359,
 360,
 362,
 365,
 370,
 371,
 382,
 383,
 390,
 391,
 392,
 393,
 448,
 449,
 450,
 453,
 464,
 465,
 470,
 480,
 481,
 492,
 504,
 505,
 506,
 507,
 508,
 513,
 528,
 532,
 533,
 537,
 548,
 581,
 614,
 623,
 628,
 629,
 634,
 635,
 677,
 712,
 713,
 750,
 762,
 773,
 774,
 789,
 790,
 794,
 795,
 797,
 801,
 813,
 843,
 888,
 904,
 905,
 906,
 928,
 932,
 943,
 956,
 964,
 969,
 981,
 1008,
 1045,
 1046,
 1049,
 1058,
 1064,
 1065,
 1072,
 1076,
 1104,
 1111,
 1114,
 1115,
 1136,
 1137,
 1146,
 1162,
 1163,
 1164,
 1169,
 1170,
 1251,
 1252,
 1253,
 1254,
 1255,
 1256,
 1257,
 1270,
 1271,
 1290,
 1291,
 1292,
 1301,
 1302,
 1328,
 1335,
 1336,
 1337,
 1341,
 1346,
 1363,
 1398,
 1399,
 1433,
 1458,
 1480,
 1511,
 1512,
 1517,
 1518,
 1604,
 1628,
 1721,
 1743,
 1768,
 2015,
 2128,
 2352,
 2626,
 2627,
 2781,
 2782,
 2800,
 2818,
 2819,
 2830,
 2842,
 2843,
 2844,
 2849,
 2858,
 2862,
 2866,
 2878,
 2887,
 2895,
 2904,
 2914,
 2915,
 2925,
 2929,
 2930,
 2942,
 2943,
 2958,
 2964,
 2967,
 2981,
 2994,
 2999,
 3015,
 3042,
 3054,
 3062,
 3063,
 4153,
 4154,
 4155,
 4156,
 4157,
 4158,
 4159,
 4160,
 4161,
 4162,
 4163,
 4164,
 4165,
 4166,
 4167,
 4168,
 4169,
 4170,
 4172,
 4173,
 4174,
 4175,
 4176,
 4178,
 4180,
 4181,
 4184,
 4186,
 4188,
 4190,
 4191,
 4193,
 4194,
 4195,
 4196,
 4197,
 4198,
 4199,
 4202,
 4208,
 4209,
 4223,
 4224,
 4226,
 4227,
 4236,
 4242,
 4244,
 4246,
 4247,
 4251,
 4257,
 4258,
 4259,
 4262,
 4269,
 4270,
 4271,
 4281,
 4282,
 4283,
 4287,
 4289,
 4298,
 4299,
 4325,
 4326,
 4327,
 4328,
 4329,
 4330,
 4331,
 4332,
 4333,
 4334,
 4335,
 4336,
 4337,
 4338,
 4341,
 4347,
 4348,
 4351,
 4354,
 4355,
 4375,
 4376,
 4377,
 4378,
 4379,
 4380,
 4381,
 4382,
 4383,
 4384,
 4385,
 4386,
 4387,
 4389,
 4394,
 4395,
 4396,
 4397,
 4406,
 4407,
 4408,
 4409,
 4410,
 4411,
 4412,
 4413,
 4414,
 4441,
 4442,
 4443,
 4444,
 4445,
 4446,
 4447,
 4454,
 4455,
 4459,
 4482,
 4483,
 4487,
 4489,
 4513,
 4514,
 4515,
 4516,
 4517,
 4518,
 4519,
 4520,
 4529,
 4552,
 4553,
 4554,
 4555,
 4556,
 4557,
 4561,
 4564,
 4580,
 4581,
 4582,
 4583,
 4584,
 4585,
 4586,
 4587,
 4588,
 4589,
 4590,
 4591,
 4592,
 4593,
 4594,
 4601,
 4623,
 4624,
 4625,
 4626,
 4627,
 4628,
 4634,
 4646,
 4647,
 4648,
 4649,
 4650,
 4651,
 4652,
 4653,
 4654,
 4655,
 4661,
 4685,
 4686,
 4687,
 4688,
 4689,
 4690,
 4691,
 4692,
 4707,
 4708,
 4709,
 4710,
 4711,
 4717,
 4739,
 4740,
 4741,
 4742,
 4743,
 4744,
 4746,
 4772,
 4773,
 4774,
 4775,
 4776,
 4778,
 4779,
 4793,
 4794,
 4795,
 4796,
 4797,
 4798,
 4799,
 4800,
 4801,
 4802,
 4803,
 4804,
 4805,
 4825,
 4826,
 4827,
 4828,
 4829,
 4830,
 4831,
 4832,
 4837,
 4850,
 4851,
 4854,
 4870,
 4871,
 4872,
 4873,
 4892,
 4913,
 4914,
 4915,
 4916,
 4917,
 4918,
 4919,
 4925,
 4935,
 4936,
 4937,
 4938,
 4939,
 4940,
 4941,
 4942,
 4955,
 4972,
 4973,
 4974,
 4975,
 4976,
 4977,
 4990,
 4991,
 4992,
 4993,
 4994,
 4995,
 4996,
 4998,
 4999,
 5006,
 5027,
 5028,
 5029,
 5030,
 5031,
 5032,
 5033,
 5052,
 5053,
 5054,
 5055,
 5056,
 5062,
 5075,
 5076,
 5077,
 5078,
 5079,
 5080,
 5081,
 5082,
 5088,
 5101,
 5102,
 5103,
 5112,
 5115,
 5128,
 5129,
 5130,
 5141,
 5142,
 5143,
 5153,
 5154,
 5155,
 5156,
 5167,
 5168,
 5169,
 5170,
 5179,
 5180,
 5186,
 5187,
 5188,
 5189,
 5196,
 5197,
 5200,
 5201,
 5202,
 5204,
 5225,
 5227,
 5230,
 5231,
 5236,
 5241,
 5245,
 5261,
 5265,
 5269,
 5271,
 5293,
 5294,
 5308,
 5317,
 5318,
 5326,
 5340,
 5341,
 5347,
 5361,
 5362,
 5363,
 5389,
 5397,
 5407,
 5409,
 5410,
 5411,
 5421,
 5422,
 5423,
 5427,
 5429,
 5440,
 5463,
 5478,
 5479,
 5482,
 5483,
 5518,
 5519,
 5533,
 5534,
 5535,
 5539,
 5559,
 5560,
 5561,
 5562,
 5570,
 5571,
 5572,
 5573,
 5574,
 5589,
 5590,
 5591,
 5609,
 5610,
 5611,
 5624,
 5632,
 5633,
 5641,
 5642,
 5643,
 5658,
 5659,
 5660,
 5661,
 5671,
 5672,
 5681,
 5682,
 5683,
 5686,
 5688,
 5695,
 5696,
 5704,
 5705,
 5712,
 5714,
 5721,
 5722,
 5723,
 5730,
 5736,
 5737,
 5738,
 5739,
 5746,
 5747,
 5754,
 5756,
 5757,
 5758,
 5765,
 5766,
 5779,
 5780,
 5782,
 5789,
 5799,
 5810,
 5815,
 5816,
 5832,
 5844,
 5845,
 5846,
 5847,
 5848,
 5859,
 5882,
 5894,
 5895,
 5898,
 5922,
 5923,
 5925,
 5931,
 5932,
 5933,
 5937,
 5938,
 5966,
 5967,
 5968,
 5969,
 5970,
 5986,
 5987,
 5988,
 5989,
 5991,
 5995,
 6008,
 6009,
 6010,
 6043,
 6044,
 6045,
 6046,
 6047,
 6048,
 6049,
 6050,
 6063,
 6064,
 6065,
 6092,
 6093,
 6094,
 6095,
 6096,
 6097,
 6098,
 6099,
 6100,
 6101,
 6102,
 6103,
 6113,
 6114,
 6135,
 6136,
 6137,
 6141,
 6173,
 6174,
 6175,
 6176,
 6177,
 6178,
 6179,
 6180,
 6181,
 6182,
 6194,
 6221,
 6222,
 6223,
 6224,
 6247,
 6248,
 6249,
 6255,
 6278,
 6279,
 6280,
 6281,
 6315,
 6316,
 6317,
 6318,
 6319,
 6331,
 6332,
 6357,
 6358,
 6359,
 6360,
 6361,
 6362,
 6363,
 6364,
 6383,
 6384,
 6398,
 6399,
 6400,
 6401,
 6402,
 6403,
 6408,
 6410,
 6430,
 6431,
 6432,
 6433,
 6434,
 6444,
 6445,
 6446,
 6452,
 6466,
 6467,
 6468,
 6480,
 6486,
 6497,
 6518,
 6519,
 6524,
 6546,
 6547,
 6563,
 6567,
 6568,
 6569,
 6570,
 6576,
 6577,
 6578,
 6596,
 6599,
 6610,
 6613,
 6618,
 6619,
 6620,
 6622,
 6630,
 6633,
 6634,
 6636,
 6645,
 6658,
 6661,
 6665,
 6668,
 6672,
 6679,
 6681,
 6682,
 6683,
 6692,
 6697,
 6704,
 6706,
 6707,
 6709,
 6710,
 6711,
 6712,
 6713,
 6714,
 6715,
 6717,
 6720,
 6721,
 6730,
 6741,
 6747,
 6749,
 6751,
 6764,
 6767,
 6771,
 6773,
 6779,
 6781,
 6788,
 6790,
 6796,
 6797,
 6798,
 6801,
 6803,
 6808,
 6809,
 6814,
 6815,
 6823,
 6830,
 6831,
 6837,
 6838,
 6839,
 6849,
 6850,
 6865,
 6871,
 6880,
 6884,
 6892,
 6903,
 6953,
 6975,
 7008,
 7096,
 7290,
 7292,
 7294,
 7295,
 7296,
 7297,
 7299,
 7300,
 7303,
 7304,
 7305,
 7310,
 7312,
 7318,
 7319,
 7320,
 7321,
 7322,
 7324,
 7328,
 7329,
 7330,
 7331,
 7332,
 7333,
 7334,
 7337,
 7338,
 7342,
 7343,
 7344,
 7354,
 7355,
 7356,
 7357,
 7358,
 7365,
 7366,
 7367,
 7371,
 7372,
 7373,
 7374,
 7377,
 7378,
 7379,
 7381,
 7382,
 7384,
 7396,
 7397,
 7398,
 7399,
 7402,
 7403,
 7404,
 7405,
 7406,
 7407,
 7408,
 7409,
 7410,
 7411,
 7412,
 7413,
 7414,
 7415,
 7418,
 7419,
 7422,
 7423,
 7424,
 7425,
 7429,
 7430,
 7431,
 7432,
 7433,
 7442,
 7443,
 7444,
 7445,
 7447,
 7448,
 7449,
 7452,
 7453,
 7454,
 7461,
 7462,
 7463,
 7464,
 7465,
 7471,
 7473,
 7474,
 7475,
 7476,
 7477,
 7480,
 7481,
 7482,
 7483,
 7484,
 7486,
 7487,
 7488,
 7489,
 7492,
 7493,
 7495,
 7496,
 7497,
 ...]

In [13]:
# define a function called "remove" which returns a cleaned dataframe without outliers
def remove(df, ls):
    ls = sorted(set(ls)) 
    Newdf = df.drop(ls)
    return df

In [15]:
df_cleaned = remove(df, index_list)
df_cleaned

,Immoweb ID,Property type,property sub-type,Price,Post code,Building condition,Kitchen type,Bedrooms,Furnished,Number of frontages,Swimming pool,Surface of the plot,Living area,Terrace_Combined,garden_label,price/m2
0,9729720,APARTMENT,PENTHOUSE,179000,1140,4,1,1,1,3,1,0,63.0,1,0,2841.27
1,9729785,APARTMENT,PENTHOUSE,255000,8370,4,1,1,1,2,1,0,42.0,1,0,6071.43
2,9729784,APARTMENT,PENTHOUSE,255000,8370,4,1,1,1,2,1,0,42.0,1,0,6071.43
3,9729780,APARTMENT,PENTHOUSE,620000,8370,4,1,3,1,2,1,0,150.0,1,0,4133.33
4,9727201,APARTMENT,PENTHOUSE,379000,1020,4,2,2,1,3,0,0,120.0,1,0,3158.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12206,7770552,APARTMENT,SERVICE_FLAT,132000,1730,6,0,1,0,3,1,0,50.0,0,0,2640.00
12207,7770553,APARTMENT,SERVICE_FLAT,177000,1730,6,0,1,0,3,1,0,64.0,1,0,2765.62
12208,7770551,APARTMENT,SERVICE_FLAT,190000,1730,6,0,2,0,3,1,0,70.0,1,0,2714.29
12209,7921693,APARTMENT,SERVICE_FLAT,1350000,5600,2,0,30,0,3,1,0,1500.0,0,0,900.00
12210,7921699,APARTMENT,SERVICE_FLAT,3100000,6940,2,0,25,0,4,1,0,1500.0,0,0,2066.67